source("renv/activate.R")
print('Welcome (back) to the "DroughtRiskAquifer" project.\n')

#--- load packages ---#
library(tidyverse)
library(lubridate)
library(tidycensus)
library(tidyUSDA)
library(data.table)
library(downloader)
library(patchwork)
library(keyring)
library(here)
library(ggplot2)
library(tmap)
library(here)
library(sf)
library(terra)
library(raster)
library(broom)
library(mgcv)
library(fixest)
library(gratia)
library(scales)
library(SPEI)
library(exactextractr)
library(geosphere)

#--- source functions ---r
source(here::here("Codes/functions.R"))

