---
output:
  pdf_document: default
  html_document: default
---

The paper aims to show the impacts of aquifer depletion on irrigated crop yields and production areas in the United States High Plains. To do so, the paper applies a panel data analysis approach to a detailed county-level dataset of saturated thickness, water deficit, yields, and land-use, using a spline model. The authors find that aquifer depletion reduces farmers' ability to cope with water deficits.

The significance and novelty of the paper stems from the clear and encompassing empirical approach to the subject matter. The depletion of the Ogallala aquifer and implications for irrigated agriculture are not new per se. A compelling quality of the paper is the clear statistical evaluation of a large panel dataset, constructed to show the negative impacts of aquifer depletion on farmer's ability to cope with water deficits, over a long period of time. To fully harness the potential of this quality for readers, the authors should mainly consider improving the clarity of the figures presented and of their description in the text, and addressing some other points that remained unclear (see details below).

\textcolor{blue}{We really appreciate your comments. Addressing them has made our paper significantly stronger. Please find our replies to your comments written in blue.}

# MAIN POINTS:

1. Abstract: 

+ "We show that aquifer depletion reduces the ability of farmers to sustain irrigated crop yields and production areas in drought years." - If stated this way, please clarify in the results and/or discussion, how causality (direction of causality, no omitted factors) is established.

\textcolor{blue}{}

+ "... in drought years" - Please define in the in the main text (or methods) how drought and drought years are defined. E.g. are any effects linked to increasing water deficits considered drought-related or only those above a certain level?

\textcolor{blue}{In this paper, drought is rather loosely defined. Also, it is not a dihcotomous definition of whether it is a drought or not. The water balance variable is used as a measure of drought and it has a continous scale. For example, water deficit of 1000 mm would be considered a "severe" drought as corn and soybean yields are estimated to be almost zero under rainfed production. Water deficit of -200 mm would be considered no drought because irrigated and rainfed yields are almost the same. We do not see the need to clearly define what drought is as it does not seem to improve our dicussions.}

2. Figure 1: This figure does not convey the effects of saturated thickness very clearly, either because the underlying analysis does not produce substantial effects, or because they are not presented in a compelling manner. It might also be helpful to use a visualization that more effectively illustrates the statements in the text. See detailed points below:

+ Please distinguish more clearly between significant and non-significant results. P. 2 states that "counties with the highest level of saturated thickness ... experience ... productivity close to rainfed yields". From the figure it is difficult to tell if the 2nd and 3rd quantile are significantly different for soybean. For corn this does not seem to be the case. Similarly, the text at the bottom of p. 2 states that "saturated thickness has a statistically significant impact on per-area irrigated crop yields in moderate to extreme drought conditions". Please clarify how the significance is evaluated here. Which range of deficits is meant by "moderate to extreme"? Are the soybean yields considered significantly different between quantiles? Are only the 1st and 3rd quantile considered significantly different for corn? - It could even be of interest to readers which results are not significant here, in contrast to the greater significance of the effects analyzed in Fig. 2 and Fig. 3.


\textcolor{blue}{
For the first point, you are right that there is not much difference between the second and third quantiles. Our intention was not to distinguish the 2nd and 3rd, but rather pointing out the fact that higher aquifer thickness counties (2nd and 3rd) have lower yields than the lowest aquifer thickness (1st quantile), and their yield are comparable to that of dryland production. Therefore, we also added 2nd quantile to our statement.
}

\textcolor{blue}{"Second, at negative water deficits, counties with the second highest and highest levels of aquifer thickness (i.e., 2nd and 3rd quantile in Figure 1 experience lower yields than counties with the lowest level of aquifer thickness (1st quantile), resulting in productivity close to rainfed yields.""}

\textcolor{blue}{For the second point, }

+ In light of point (1.a), please also consider whether additional panels showing tests for specific hypotheses or other visual aids could make the Fig. 1 more accessible to readers with regards to the statements made. The figure is quite crowded, with many confidence bands overlapping. Currently, it takes time for readers to parse where the confidence bands for some of the plot lines end. The figure could be of greater benefit to readers if it was more accessible.

\textcolor{blue}{We agree with this comment. It is important to have all the four curves in the same panel as that would allow the readers to compare them easily. However, with confidence intervals, the figure was too crowded. Therefore, we took out the confidence intervals around the curves. We then put estiamted curves with confidence intervals individually in separate panels in the appendix.}

+ How were confidence bands determined? Were additional tests performed to evaluate their validity? Please consider showing individual data points.

\textcolor{blue}{They are derived from the standard error of the coefficients in the model represented by equation 1, which is the standard in constructing the confidence interval. There is no other way of estimating confidence interval of the estimated curves that come purely from statistically estimated model. Also, there is no way of validating such confidence intervals. The role of confidence interval here is to quantify the uncertainty of the point estimates and nothing more.}

+ P. 2 states that "for water deficits above around 400mm, yield changes become negative for counties with the lowest levels of saturated thickness (i.e., 1st quantile in Figure 1). This reflects the restrictions that lower saturated thickness and associated reductions in well yields place on farmers ability to fully meet crop water requirements during periods of more severe or extended precipitation deficits". How valid is this interpretation in view of the fact that these counties see a similarly large yield decrease below 400mm and that counties with the highest levels of saturated thickness even see a much stronger increase in yields with increasing deficits?

\textcolor{blue}{We believe, our interpretation is valid. When you mention "similarly large yield decrease," you are talking about "declines" in reponse to the opposite directions of water deficit. Yield increases as water defitic increases at first, and then starts to decline. This can be due to "increased evapotranspiration and associated biomass accumulation, reductions of heat-related stressors" as mentioned in our manuscript. This holds for all the three aquifer thickness categories. However, if aquifer thickness is low and as a consequence well yield is low, farmers cannot cathch up with high water demand, leading to declining yield caused by highr water deficit. The figure shows that lower aquifer thickness quantile starts to experinence a decline in yield at lower water deficits than the second and third.} 

+ Please clarify in the legend or caption that the quantiles indicate levels of saturated thickness.

\textcolor{blue}{Thank you for this comment. We made changes to all the relevant figures according to this suggestion.}

3. Figure 2: Please clarify in the texthow the significance of reductions in the share of irrigated acres is evaluated (e.g. relative to which aquifer depletion level(s)?), and at which level of aquifer depletion the reduced irrigation share becomes significant for each crop.


4. Figure 3:

+ Please clarify why this figure has no confidence bands. The text describes it as a combination of the effects shown in Fig. 1 and Fig. 2, which both have confidence bands. Please clarify how significance is evaluated.

```{r}
We should have had confidence intervals for this figure as well. However, in reponse to your earlier comments, we have decided to not present confidence intervals for this figure just like we did for Figure 1 because the figure would look too busy.
```
+ Relatedly, the text states that deficits beyond 200mm yield significant reductions in corn production. 200mm is where the curves intersect. Please clarify if this actually is also where significance starts, or if significance starts at a higher deficit.

\textcolor{blue}{}

+ Please double-check if the y-axis label is correct. The label ("yield (tonne/ha)") is the same as for Fig. 1, which makes it difficult to distinguish the different results presented in Fig. 1 and 3.


5. Discussion: 

+ P. 6: "Previous research focused on impacts..." this sentence largely repeats a sentence from the introduction, not in the same words but in content (and using the same references). Please consider removing or modifying the sentence to add new insights for readers.

\textcolor{red}{Tim, they look different enough to me. And who cares if we repated the same thing as long as it is important to emphasize.}

+ P. 6: "... demonstrate that the relationship between aquifer saturated thickness and drought impacts is highly nonlinear when accounting for farmers decisions about irrigated production areas. This indicates that sustainable groundwater conservation efforts [...] should be targeted in space and time to avoid depletion exceeding critical thresholds ..." Is the assumption of non-linearity tested? It is difficult to assess the validity of this statement based on the figures provided. Please clarify (e.g. in the results) what supports this statement.



6. Methods - data sets: 

+ P. 7: "For counties that do not meet this condition, only rainfed yield observations are obtained to avoid the possibility that irrigated production may be only partly dependent on use of groundwater from the HPA." - Please consider whether this assumption could bias results and how potential biases can be ruled out.

\textcolor{blue}{
This will not bias our main part of the regression analysis in any way. Dryland yields are part of the modeling just to illustrate how powerful irrigation is. As you know, this is not our main results. The identification of yield reposne to water deficit for the three awuifer thickness catoegories is coming solely drom the irrigated production data.
}

+ P. 9: Saturated thickness data - the number of monitoring wells would be of interest for readers to better judge the data, if available.

\textcolor{blue}{}

7. Methods - regression models:

+ P. 9: If the model includes fixed effects, how are the single plot lines for each category shown in Fig. 1 derived? 

\textcolor{blue}{
That is because a single county-year was selected in predicting yields. We could pick any county-year without changing any of the conclusions we are drawing. This is because fixed effects are merely a shifter. The relative difference in yield across all the categories is the same no matter what county-year we pick. The curvature will of course be the same as well.  
}

+ P. 9: Developments over time and independent variables: Please address early in the main text which overall trends shape developments in the aquifer studied. Please include key references about the case study region to inform this, such as Mrad et al. (2020), doi.org/10.1073/pnas.2008383117. In light of this, please discuss the appropriateness of the approach. The model accounts for year-specific "shocks", but not other developments over time (e.g. lagged effects, gradual depletion trends, the introduction of regulation, etc.). Relatedly, the analysis only saturated thickness and water deficits to explain yields, rather than adding more explanatory variables. The advantage of the approach taken here might be the simplicity and clarity of assumptions. Readers would benefit from a short explicit discussion.

\textcolor{red}{Tim, I don't know what he wants from the first sentence. I don't really care what he is talking about and I think it is irrelevant. But, if you can somehow address this with some citations including the one he suggested, that would be great. He is probably one of the authors of that paper (he is not an economist, his understanding of the methods and results is not of the one who were trained as an economist.).}

\textcolor{red}{Tim, can you address this? "Relatedly, the analysis only saturated thickness and water deficits to explain yields, rather than adding more explanatory variables. The advantage of the approach taken here might be the simplicity and clarity of assumptions. Readers would benefit from a short explicit discussion.". I believe you already had sound arguments when we zoomed last time.}

+ P. 10: Please provide details on the basis functions in the methods section or the supplement. 

\textcolor{blue}{We added appendix B in response.}

8. Supplementary information: Please also consider providing additional information to give readers more clarity on the points outlined above in the supplementary information.

\textcolor{blue}{Thank you for this suggestion. We added Appendix, which we belive made our paper much stronger.}

## MINOR POINTS:

\textcolor{blue}{Thank you for noticing there errors. All of them are fixed in the latest manuscript.}

+ [x] M1. Please add line numbers.

+ [x] M2. P. 2: Missing closing parenthesis after "(i.e., 3rd quantile ..."

+ [ ] M3. Fig. 1, 2, 3, and 5: Please add panel tags ("a", "b" ...) to make it easier for readers to understand the captions.

+ [x] M4. Fig. 3: Closing parenthesis of y-axis title missing

+ [ ] M5. P. 9: "WB" and "ST" should not be in italics, unless "W", "B", "S", and "T" are separate variables

+ [x] M6. P. 9: "[0 - 33.3%)j" - the "j" does not seem to belong here

+ [x] M7. P. 9: "with sigma_j represents the category specific intercept" should be "with sigma_j representing the category-specific intercept" or something similar

+ [x] M8. P. 9: "under the generalize additive model framework" should be "generalized" and "modeling" or something similar

+ [ ] M9. P. 9: What is "mu_t" in equation 2? Should "theta_t" in equation 1 be "mu_t"? Because "theta_jk" is already the spline basis function.

+ [x] M10. P. 9: One reference seems to be missing (the text includes "(REF)").
