---
title: "Prepare SSURGO Data"
author: "Taro Mieno"
output:
  html_document:
    number_sections: yes
    theme: flatly
    highlight: zenburn
    toc_float: yes
    toc: yes
    toc_depth: 3
geometry: margin=1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
  tidy = FALSE,
  cache.lazy = FALSE,
  #--- figure ---#
  dpi = 400,
  fig.width = 7.5,
  fig.height = 5,
  out.width = "750px",
  out.height = "500px"
)
```

# Prepare  

## Read the counties sf
```{r}
all_counties <-
  readRDS(here("Shared/Data/ProcessedData/base_counties.rds")) %>%
  st_as_sf() %>%
  dplyr::mutate(geometry = st_make_valid(geometry)) %>%
  st_transform(4326)
```

```{r}
get_ssurgo_props <- function(field, vars) {
  # Get SSURGO mukeys for polygon intersection
  download_try <-
    soilDB::SDA_spatialQuery(
      field,
      what = "geom",
      db = "SSURGO"
    )

  if ("try-error" %in% class(download_try)) {
    #* county too large fot a single download
    print("County too large. Breaking it into pieces and work on them separately.")

    grids <-
      st_bbox(field) %>%
      st_as_sfc() %>%
      st_make_grid(n = c(3, 3))

    field_parts <-
      st_intersection(grids, field) %>%
      st_make_valid() %>%
      st_as_sf()

    ssurgo_geom <-
      lapply(
        1:nrow(field_parts),
        \(x) {
          print(paste0("working on ", x))
          field_part_w <- field_parts[x, ]
          download_try <-
            soilDB::SDA_spatialQuery(
              field_part_w,
              what = "geom",
              db = "SSURGO"
            ) %>%
            st_make_valid() %>%
            st_intersection(field_part_w, .)
        }
      ) %>%
      bind_rows() %>%
      st_make_valid() %>%
      dplyr::mutate(
        area = as.numeric(st_area(.)),
        area_weight = area / sum(area)
      )

    ssurgo_data_sum <- get_summarized_ssurgo(ssurgo_geom, vars)
  } else {
    ssurgo_geom <-
      download_try %>%
      st_make_valid() %>%
      st_intersection(field, .) %>%
      mutate(
        area = as.numeric(st_area(.)),
        area_weight = area / sum(area)
      )

    ssurgo_data_sum <- get_summarized_ssurgo(ssurgo_geom, vars)
  }

  ssurgo_data_sum[, sc_code := field$sc_code]
  return(ssurgo_data_sum)
}

get_summarized_ssurgo <- function(ssurgo_geom, vars) {
  # Get soil properties for each mukey
  mukeydata <-
    soilDB::get_SDA_property(
      property = vars,
      method = "Weighted Average",
      mukeys = unique(ssurgo_geom$mukey),
      top_depth = 0,
      bottom_depth = 150
    )

  ssurgo_data <- left_join(ssurgo_geom, mukeydata, by = "mukey")

  ssurgo_data_sum <-
    ssurgo_data %>%
    data.table() %>%
    .[,
      lapply(.SD, function(x) weighted.mean(x, w = area_weight, na.rm = TRUE)),
      .SDcols = vars
    ] %>%
    data.table()
  return(ssurgo_data_sum)
}
```

## Download

```{r download, cache = TRUE}
vars <- c("sandtotal_r", "silttotal_r", "claytotal_r", "awc_r", "om_r", "dbovendry_r")

parallel::mclapply(
  1:nrow(all_counties),
  \(x) {
    print(x)
    file_name <- here::here(paste0("Shared/Data/RawData/SSURGO/ssurgo_", x, "rds"))
    if (!file.exists(file_name)) {
      print(paste0("working on ", x))
      temp <- get_ssurgo_props(all_counties[x, ], vars)
      saveRDS(temp, here::here(paste0("Shared/Data/RawData/SSURGO/ssurgo_", x, "rds")))
    } else {
      temp <- readRDS(file_name)
      if (ncol(temp) < 7) {
        temp <- get_ssurgo_props(field = all_counties[x, ], vars)
        saveRDS(temp, paste0("Shared/Data/RawData/SSURGO/ssurgo_", x, "rds"))
      } else {
        print(paste0("skipping ", x))
      }
    }
  },
  mc.cores = 6,
  mc.preschedule = FALSE
)

lapply(
  1:nrow(all_counties),
  \(x) {
    print(x)
    file_name <- paste0("Shared/Data/RawData/SSURGO/ssurgo_", x, "rds")
    if (!file.exists(file_name)) {
      temp <- get_ssurgo_props(field = all_counties[x, ], vars)
      saveRDS(temp, paste0("Shared/Data/RawData/SSURGO/ssurgo_", x, "rds"))
    } else {
      temp <- readRDS(file_name)
      if (ncol(temp) < 7) {
        temp <- get_ssurgo_props(field = all_counties[x, ], vars)
        saveRDS(temp, paste0("Shared/Data/RawData/SSURGO/ssurgo_", x, "rds"))
      }
    }
  }
)
```

# save the SSURGO data

```{r }
ssurgo_soil <-
  fs::dir_ls("Shared/Data/RawData/SSURGO") %>%
  purrr::map(readRDS) %>%
  rbindlist()

saveRDS(ssurgo_soil, here("Shared/Data/ProcessedData/ssurgo_soil.rds"))
```

