---
title: "Regression Analysis and Prediction"
author: "Taro Mieno"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
  tidy = FALSE,
  cache.lazy = FALSE,
  #--- figure ---#
  dpi = 400,
  fig.width = 7.5,
  fig.height = 5,
  out.width = "750px",
  out.height = "500px"
)
```

# Prepare data

```{r}
#--- read data ---#
final_data <-
  here("Shared/Data/ProcessedData/final_data.rds") %>%
  # here::here("../Shared/Data/ProcessedData/final_data.rds") %>%
  readRDS()

#--- Data used for regression analysis ---#
reg_data <-
  prepare_reg_data(
    data = final_data,
    sat_thld_m = 12, # saturated thickness has to be at least 12 meters
    ir_share_thld = 0.75, # at least 75% of total county area has to be overlapped with HPA
    balance_thld = c(-1200, 200),
    sat_cat_num = 3,
    state_ls =
      list(
        corn = c("CO", "KS", "NE", "NM", "SD", "TX", "WY"),
        soy = c("KS", "NE", "TX")
      )
  ) %>%
  data.table()

saveRDS(reg_data, file = here::here("Shared/Data/reg_data.rds"))
```

# Regression and prediciton: Corn

## Intensive Margin

### Regression

```{r}
data_corn <-
  reg_data[crop_type == "corn", reg_data_y][[1]] %>%
  copy() %>%
  #--- bu/acre to tonne/ha ---#
  .[, yield := yield * 12.553 / 200] %>%
  .[, type := "Corn"] %>%
  .[, dry_or_not := fifelse(sat_cat == "dryland", 1, 0)] %>%
  .[, sc_dry := paste0(sc_code, "_", dry_or_not)] %>%
  .[, balance := -balance]

#--- define the semi-parametric portion of the model ---#
semi_formula <-
  formula(yield ~ s(balance, by = sat_cat, k = 3, m = 2))

#--- semi-parametric FE wih fixest ---#
semi_res_corn <-
  semi_ols(
    semi_formula = semi_formula,
    c_formula = "i(sat_cat, ref = 'dryland') + i(year) + i(sc_dry)",
    # fe = "",
    cluster = "sc_dry",
    data = data_corn
  )

#--- main regression results ---#
y_res_int <- semi_res_corn$fe_res

r2_corn_wb <- r2(y_res_int, type = "r2")
```

### Prediction

```{r}
gam_y_res <- semi_res_corn$gam_res

sc_dry_base <- data_corn[sc_code == "31011", sc_dry][1]
sc_base <- "31011"

#--- raw data for prediction ---#
data_for_pred_corn <-
  CJ(
    balance = seq(min(data_corn$balance), max(data_corn$balance), length = 50),
    sat_cat = unique(data_corn$sat_cat)
  ) %>%
  # .[, sat := parse_number(gsub("\\,.*", "", sat_cat))] %>%
  .[, sat := case_when(
    sat_cat == "[39.4,82]" ~ 40,
    sat_cat == "(82,194]" ~ 194,
    sat_cat == "(194,708]" ~ 348,
    sat_cat == "dryland" ~ 0
  )] %>%
  .[is.na(sat), sat := 0] %>%
  # === can be any sc_code (need to shift yield for "average" county) ===#
  .[, sc_code := sc_base] %>%
  .[, sc_dry := sc_dry_base] %>%
  # === can be any year (need to shift yield for "average" year) ===#
  .[, year := 2009] %>%
  # === fake yield data (necessary to take advantage of predict.gam) ===#
  .[, yield := 0] %>%
  .[, type := "pred"] %>%
  .[, dry_or_not := fifelse(sat_cat == "dryland", 1, 0) %>% factor()]

#--- create bases  ---#
yhat_data_corn <-
  gen_smooth_data(
    data = data_for_pred_corn,
    gam_res = gam_y_res
  ) %>%
  .$data

y_hat_with_se <- predict(y_res_int, newdata = yhat_data_corn, se.fit = TRUE)

yhat_data_corn[, `:=`(
  y_hat = y_hat_with_se$fit,
  y_hat_se = y_hat_with_se$se.fit
)]

yhat_data_corn[, sat_cat_q :=
  as.numeric(sat_cat) %>%
  ordinal() %>%
  paste0(., " quintile")]
```

```{r}
(
  g_yield_balance_corn <-
    ggplot(yhat_data_corn) +
    geom_ribbon(
      aes(
        ymin = y_hat - 1.96 * y_hat_se,
        ymax = y_hat + 1.96 * y_hat_se,
        x = balance,
        fill = factor(sat_cat_q)
      ),
      alpha = 0.3
    ) +
    geom_line(aes(
      y = y_hat,
      x = balance,
      color = factor(sat_cat_q)
    )) +
    xlab("Water Balance") +
    ylab("Yield (tonne/ha)") +
    scale_color_discrete(name = "") +
    scale_fill_discrete(guide = "none") +
    theme(
      legend.position = "bottom"
    ) +
    theme_bw()
)
```

## Extensive Margin (acreage share)

```{r}
ir_share_data_corn <-
  data_corn %>%
  .[ir == "ir" & ir_area_ratio >= 0.75, ] %>%
  .[, balance_avg := mean(balance), by = sc_code] %>%
  .[, type := "Corn"]

ir_share_res_corn <-
  gam(
    acres_ratio ~
      s(sat, k = 3, m = 2) +
      s(balance_avg, k = 3, m = 2) +
      factor(state_name) +
      factor(year),
    data = ir_share_data_corn,
    # weight = ~acres,
    family = binomial
  )
```

### Prediction

```{r}
share_pred_data_corn <-
  CJ(
    sat = seq(
      min(ir_share_data_corn$sat),
      max(ir_share_data_corn$sat),
      length = 100
    ),
    balance_avg = mean(ir_share_data_corn$balance_avg),
    year = 2016,
    state_name = "Nebraska"
  )

ir_share_hat_data <-
  predict(
    ir_share_res_corn,
    newdata = share_pred_data_corn,
    type = "response",
    se.fit = TRUE
  )

share_pred_data_corn[, ir_share_hat := ir_share_hat_data$fit]
share_pred_data_corn[, ir_share_hat_se := ir_share_hat_data$se.fit]

ggplot(share_pred_data_corn[sat <= 600, ]) +
  geom_line(aes(y = ir_share_hat, x = sat * 0.3048)) +
  geom_ribbon(
    aes(
      ymin = ir_share_hat - 1.96 * ir_share_hat_se,
      ymax = ir_share_hat + 1.96 * ir_share_hat_se,
      x = sat * 0.3048
    ),
    alpha = 0.4
  ) +
  ylim(0, NA) +
  xlab("Saturated Thickness (meter)") +
  ylab("Share of Irrigated Acres")
```

## Average (rainfed and irrigated combined)

```{r}
data_corn_total <-
  yhat_data_corn[, .(y_hat, y_hat_se, balance, sat_cat, sat, type, year)] %>%
  .[, state_name := "Nebraska"] %>%
  .[, balance_avg := mean(balance)] %>%
  .[, c("ir_share_hat", "ir_share_hat_se") := predict(ir_share_res_corn, newdata = ., type = "response", se.fit = TRUE)]

data_ir_corn <-
  data_corn_total[sat_cat != "dryland"] %>%
  setnames(c("y_hat", "y_hat_se"), c("y_hat_ir", "y_hat_se_ir"))

data_dry_corn <-
  data_corn_total[sat_cat == "dryland"] %>%
  .[, .(y_hat, y_hat_se, balance)] %>%
  setnames(c("y_hat", "y_hat_se"), c("y_hat_dry", "y_hat_se_dry"))

data_avg_yield_corn <-
  data_dry_corn[data_ir_corn, on = "balance"] %>%
  .[, avg_yield := ir_share_hat * y_hat_ir + (1 - ir_share_hat) * y_hat_dry] %>%
  .[, type := "Corn"]
```

# Regression and prediciton: Soybean

## Intensive margin

### Regression

```{r}
data_soy <-
  reg_data[crop_type == "soy", reg_data_y][[1]] %>%
  copy() %>%
  #--- bu/acre to tonne/ha ---#
  .[, yield := yield * 12.553 / 200] %>%
  .[, type := "Soybean"] %>%
  .[, dry_or_not := fifelse(sat_cat == "dryland", 1, 0)] %>%
  .[, sc_dry := paste0(sc_code, "_", dry_or_not)] %>%
  .[, balance := -balance]

#--- define the semi-parametric portion of the model ---#
semi_formula <- formula(yield ~ s(balance, by = sat_cat, k = 3, m = 2))

#--- semi-parametric FE wih fixest ---#
semi_res_soy <-
  semi_ols(
    semi_formula = semi_formula,
    c_formula = "i(sat_cat, ref = 'dryland') + i(year) + i(sc_dry)",
    # fe = "",
    cluster = "sc_dry",
    data = data_soy
  )

#--- main regression results ---#
y_res_int <- semi_res_soy$fe_res

r2_soy_wb <- r2(y_res_int, type = "r2")
```

### Prediction

```{r}
gam_y_res <- semi_res_soy$gam_res

sc_dry_base <- data_soy[sc_code == "31011", sc_dry][1]
sc_base <- "31011"

#--- raw data for prediction ---#
data_for_pred_soy <-
  CJ(
    balance = seq(min(data_soy$balance), max(data_soy$balance), length = 50),
    sat_cat = unique(data_soy$sat_cat)
  ) %>%
  .[, sat := case_when(
    sat_cat == "[39.4,82]" ~ 40,
    sat_cat == "(82,194]" ~ 194,
    sat_cat == "(194,708]" ~ 348,
    sat_cat == "dryland" ~ 0
  )] %>%
  .[is.na(sat), sat := 0] %>%
  # === can be any sc_code (need to shift yield for "average" county) ===#
  .[, sc_code := data_soy$sc_code[1]] %>%
  .[, sc_dry := data_soy$sc_dry[1]] %>%
  # === can be any year (need to shift yield for "average" year) ===#
  .[, year := 2009] %>%
  # === fake yield data (necessary to take advantage of predict.gam) ===#
  .[, yield := 0] %>%
  .[, type := "pred"] %>%
  .[, dry_or_not := fifelse(sat_cat == "dryland", 1, 0) %>% factor()]

#--- create bases  ---#
yhat_data_soy <-
  gen_smooth_data(
    data = data_for_pred_soy,
    gam_res = gam_y_res
  ) %>%
  .$data

y_hat_with_se <- predict(y_res_int, newdata = yhat_data_soy, se.fit = TRUE)

yhat_data_soy[, `:=`(
  y_hat = y_hat_with_se$fit,
  y_hat_se = y_hat_with_se$se.fit
)]

yhat_data_soy[, sat_cat_q :=
  as.numeric(sat_cat) %>%
  ordinal() %>%
  paste0(., " quintile")]
```


```{r}
(
  g_yield_balance_soy <-
    ggplot(yhat_data_soy) +
    geom_ribbon(
      aes(
        ymin = y_hat - 1.96 * y_hat_se,
        ymax = y_hat + 1.96 * y_hat_se,
        x = balance,
        fill = factor(sat_cat_q)
      ),
      alpha = 0.3
    ) +
    geom_line(aes(
      y = y_hat,
      x = balance,
      color = factor(sat_cat_q)
    )) +
    xlab("balance") +
    ylab("Yield (tonne/ha)") +
    scale_color_discrete(name = "") +
    theme(
      legend.position = "bottom"
    )
)
```

## Extensive Margin (acreage share)

```{r}
ir_share_data_soy <-
  data_soy %>%
  .[ir == "ir" & ir_area_ratio >= 0.75, ] %>%
  .[, balance_avg := mean(balance), by = sc_code] %>%
  .[, type := "Soybean"]

ir_share_res_soy <-
  gam(
    acres_ratio ~
      s(sat, k = 4, m = 2) +
      s(balance_avg, k = 3, m = 2) +
      factor(state_name) +
      factor(year),
    data = ir_share_data_soy,
    # weight = ~acres,
    family = binomial
  )
```

### Prediction

```{r}
share_pred_data_soy <-
  CJ(
    sat = seq(
      min(ir_share_data_soy$sat),
      max(ir_share_data_soy$sat),
      length = 100
    ),
    balance_avg = mean(ir_share_data_soy$balance_avg),
    year = 2016,
    state_name = "Nebraska"
  )

ir_share_hat_data <-
  predict(
    ir_share_res_soy,
    newdata = share_pred_data_soy,
    type = "response",
    se.fit = TRUE
  )

share_pred_data_soy[, ir_share_hat := ir_share_hat_data$fit]
share_pred_data_soy[, ir_share_hat_se := ir_share_hat_data$se.fit]

ggplot(share_pred_data_soy[sat <= 600, ]) +
  geom_line(aes(y = ir_share_hat, x = sat * 0.3048)) +
  geom_ribbon(
    aes(
      ymin = ir_share_hat - 1.96 * ir_share_hat_se,
      ymax = ir_share_hat + 1.96 * ir_share_hat_se,
      x = sat * 0.3048
    ),
    alpha = 0.4
  ) +
  ylim(0, NA) +
  xlab("Saturated Thickness (meter)") +
  ylab("Share of Irrigated Acres")
```

## Average (rainfed and irrigated combined)

```{r}
data_soy_total <-
  yhat_data_soy[, .(y_hat, y_hat_se, balance, sat_cat, sat, type, year)] %>%
  .[, state_name := "Nebraska"] %>%
  .[, balance_avg := mean(balance)] %>%
  .[, c("ir_share_hat", "ir_share_hat_se") := predict(ir_share_res_soy, newdata = ., type = "response", se.fit = TRUE)]

data_ir_soy <-
  data_soy_total[sat_cat != "dryland"] %>%
  setnames(c("y_hat", "y_hat_se"), c("y_hat_ir", "y_hat_se_ir"))

data_dry_soy <-
  data_soy_total[sat_cat == "dryland"] %>%
  .[, .(y_hat, y_hat_se, balance)] %>%
  setnames(c("y_hat", "y_hat_se"), c("y_hat_dry", "y_hat_se_dry"))

data_avg_yield_soy <-
  data_dry_soy[data_ir_soy, on = "balance"] %>%
  .[, avg_yield := ir_share_hat * y_hat_ir + (1 - ir_share_hat) * y_hat_dry] %>%
  .[, type := "Soybean"]
```

# Save the results

```{r}
reg_results_data <-
  data.table(
    crop = c("Corn", "Soybean"),
    data = list(data_corn, data_soy),
    semi_res = list(semi_res_corn, semi_res_soy),
    yhat_data = list(yhat_data_corn, yhat_data_soy),
    share_data = list(ir_share_data_corn, ir_share_data_soy),
    share_res = list(ir_share_res_corn, ir_share_res_soy),
    share_pred_data = list(share_pred_data_corn, share_pred_data_soy),
    avg_yield_data = list(data_avg_yield_corn, data_avg_yield_soy)
  )

saveRDS(reg_results_data, here::here("Shared/Results/reg_results_data.rds"))
```

