---
title: "Regression Analysis and Prediction"
author: "Taro Mieno"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
  tidy = FALSE,
  cache.lazy = FALSE,
  #--- figure ---#
  dpi = 400,
  fig.width = 7.5,
  fig.height = 5,
  out.width = "750px",
  out.height = "500px"
)
```

# Prepare data

```{r}
#--- read data ---#
final_data <-
  here("Shared/Data/ProcessedData/final_data.rds") %>%
  # here::here("../Shared/Data/ProcessedData/final_data.rds") %>%
  readRDS()

#--- Data used for regression analysis ---#
reg_data <-
  prepare_reg_data(
    data = final_data,
    sat_thld_m = 12, # saturated thickness has to be at least 12 meters
    ir_share_thld = 0.75, # at least 75% of total county area has to be overlapped with HPA
    balance_thld = c(-1200, 200),
    sat_cat_num = 3,
    state_ls =
      list(
        corn = c("CO", "KS", "NE", "NM", "SD", "TX", "WY"),
        soy = c("KS", "NE", "TX")
      )
  ) %>%
  data.table()

saveRDS(reg_data, file = here::here("Shared/Data/reg_data.rds"))
```

```{r}
plan(multicore, workers = parallel::detectCores() - 2)
```

# Regression and prediciton: Corn

## Yield

```{r}
set.seed(283397)

#--- global parameters ---#
sc_base <- "31011"
sc_dry_base <- "31011_0"

all_results <-
  reg_data %>%
  setnames("crop_type", "crop") %>%
  #--- further necessary transformation ---#
  dplyr::mutate(data = purrr::map(
    reg_data_y,
    \(reg_data_y) {
      copy(reg_data_y) %>%
        #--- bu/acre to tonne/ha ---#
        .[, yield := yield * 12.553 / 200] %>%
        .[, dry_or_not := fifelse(sat_cat == "dryland", 1, 0)] %>%
        .[, sc_dry := paste0(sc_code, "_", dry_or_not)] %>%
        .[, state_year := paste0(state_name, "_", year)] %>%
        .[, balance := -balance]
    }
  )) %>%
  #--- bootstrapped data ---#
  dplyr::mutate(boot_data = purrr::map(
    data,
    \(data) {
      replicate(20, boot(data), simplify = FALSE)
      # replicate(1000, boot(data), simplify = FALSE)
    }
  )) %>%
  #--- analysis on each of the bootstrapped datasets ---#
  dplyr::mutate(results = purrr::map(
    boot_data,
    \(boot_data) {
      parallel::mclapply(
        1:length(boot_data),
        \(x) {
          print(x)
          run_analysis(boot_data[[x]])
        },
        mc.cores = 5
      )
    }
  )) %>%
  #--- extract ---#
  .[, .(crop, data, results)] %>%
  dplyr::mutate(
    yield_response = purrr::map(
      results,
      \(x) {
        purrr::map(x, 1) %>% rbindlist()
      }
    ),
    share = purrr::map(
      results,
      \(x) {
        purrr::map(x, 2) %>% rbindlist()
      }
    ),
    avg_yield = purrr::map(
      results,
      \(x) {
        purrr::map(x, 3) %>% rbindlist()
      }
    )
  ) %>%
  dplyr::mutate(yield_response_sum = purrr::map(
    yield_response,
    \(yield_response) {
      yield_response[, .(
        y_hat = mean(y_hat),
        lower = quantile(y_hat, prob = 0.025),
        upper = quantile(y_hat, prob = 0.975),
        dif_y_hat = mean(dif_y_hat),
        dif_lower = quantile(dif_y_hat, prob = 0.025),
        dif_upper = quantile(dif_y_hat, prob = 0.975)
      ),
      by = .(balance, sat, sat_cat)
      ]
    }
  )) %>%
  dplyr::mutate(share_sum = purrr::map(
    share,
    \(share) {
      share[, .(
        ir_share_hat = mean(ir_share_hat),
        lower = quantile(ir_share_hat, prob = 0.025),
        upper = quantile(ir_share_hat, prob = 0.975)
      ),
      by = .(sat)
      ]
    }
  )) %>%
  dplyr::mutate(avg_yield_sum = purrr::map(
    avg_yield,
    \(avg_yield) {
      avg_yield[, .(
        avg_yield = mean(avg_yield),
        lower = quantile(avg_yield, prob = 0.025),
        upper = quantile(avg_yield, prob = 0.975),
        dif_avg_yield = mean(dif_avg_yield),
        dif_lower = quantile(dif_avg_yield, prob = 0.025),
        dif_upper = quantile(dif_avg_yield, prob = 0.975)
      ),
      by = .(balance, sat)
      ]
    }
  ))
# all_results[1, crop := "Corn"]
# all_results[2, crop := "Soybean"]
```

```{r}
saveRDS(all_results, "Shared/Results/all_results.rds")
```

