# Testing of the significance of yield difference (total)

```{r}
results_data <- readRDS("Shared/Results/reg_results_data.rds")
```

## Corn

```{r}
#--- corn ---#
data_corn <- results_data[crop == "Corn", data][[1]]

#--- soy ---#
data_soy <- results_data[crop == "Soybean", data][[1]]

#--- sc_code and sc_dry (same for corn and soybean) ---#
#* both corn and soybean data have them
sc_dry_base <- data_corn[sc_code == "31011", sc_dry][1]
sc_base <- "31011"
```


```{r}
bootstrap <- function(i, data, sc_base, sc_dry_base) {
  #++++++++++++++++++++++++++++++++++++
  #+ Debug
  #++++++++++++++++++++++++++++++++++++
  # i <- 1
  # data <- data_corn
  # sc_base <- sc_base_corn
  # sc_dry_base <- sc_dry_base_corn
  #++++++++++++++++++++++++++++++++++++
  #+ Main
  #++++++++++++++++++++++++++++++++++++
  print(i)

  sc_ls <- data[, sc_code] %>% unique()

  data_boot <-
    rbind(
      data[sc_code %in% sample(sc_ls, length(sc_ls) - 1, replace = TRUE), ],
      data[sc_code == sc_base, ],
      data[sat_cat == "dryland", ]
    )

  #--- define the semi-parametric portion of the model ---#
  semi_formula <-
    formula(yield ~ s(balance, by = sat_cat, k = 3, m = 2))

  #--- semi-parametric FE wih fixest ---#
  semi_res <-
    semi_ols(
      semi_formula = semi_formula,
      c_formula = "i(sat_cat, ref = 'dryland') + i(year) + i(sc_dry)",
      # fe = "",
      cluster = "sc_dry",
      data = data_boot
    )

  #--- main regression results ---#
  y_res_int <- semi_res$fe_res

  r2_corn_wb <- r2(y_res_int, type = "r2")

  #--- raw data for prediction ---#
  data_for_pred <-
    CJ(
      balance = seq(min(data_boot$balance), max(data_boot$balance), length = 50),
      sat_cat = unique(data_boot$sat_cat)
    ) %>%
    # .[, sat := parse_number(gsub("\\,.*", "", sat_cat))] %>%
    .[, sat := case_when(
      sat_cat == "[39.4,82]" ~ 40,
      sat_cat == "(82,194]" ~ 194,
      sat_cat == "(194,708]" ~ 348,
      sat_cat == "dryland" ~ 0
    )] %>%
    .[is.na(sat), sat := 0] %>%
    # === can be any sc_code (need to shift yield for "average" county) ===#
    .[, sc_code := sc_base] %>%
    .[, sc_dry := sc_dry_base] %>%
    # === can be any year (need to shift yield for "average" year) ===#
    .[, year := 2009] %>%
    # === fake yield data (necessary to take advantage of predict.gam) ===#
    .[, yield := 0] %>%
    .[, type := "pred"] %>%
    .[, dry_or_not := fifelse(sat_cat == "dryland", 1, 0) %>% factor()]

  #--- create bases  ---#
  yhat_data <-
    gen_smooth_data(
      data = data_for_pred,
      gam_res = semi_res$gam_res
    ) %>%
    .$data

  y_hat_with_se <- predict(y_res_int, newdata = yhat_data, se.fit = TRUE)

  yhat_data[, `:=`(
    y_hat = y_hat_with_se$fit,
    y_hat_se = y_hat_with_se$se.fit
  )]

  yhat_data[, sat_cat_q :=
    as.numeric(sat_cat) %>%
    ordinal() %>%
    paste0(., " quintile")]

  ir_share_data <-
    data_boot %>%
    .[ir == "ir" & ir_area_ratio >= 0.75, ] %>%
    .[, balance_avg := mean(balance), by = sc_code] %>%
    .[, type := "Corn"]

  ir_share_res <-
    gam(
      acres_ratio ~
        s(sat, k = 3, m = 2) +
        s(balance_avg, k = 3, m = 2) +
        factor(state_name) +
        factor(year),
      data = ir_share_data,
      # weight = ~acres,
      family = binomial
    )

  share_pred_data_corn <-
    CJ(
      sat = seq(
        min(ir_share_data$sat),
        max(ir_share_data$sat),
        length = 100
      ),
      balance_avg = mean(ir_share_data$balance_avg),
      year = 2016,
      state_name = "Nebraska"
    )

  ir_share_hat_data <-
    predict(
      ir_share_res,
      newdata = share_pred_data_corn,
      type = "response",
      se.fit = TRUE
    )

  data_total <-
    yhat_data[, .(y_hat, y_hat_se, balance, sat_cat, sat, type, year)] %>%
    .[, state_name := "Nebraska"] %>%
    .[, balance_avg := mean(balance)] %>%
    .[, c("ir_share_hat", "ir_share_hat_se") := predict(ir_share_res, newdata = ., type = "response", se.fit = TRUE)]

  data_ir <-
    data_total[sat_cat != "dryland"] %>%
    setnames(c("y_hat", "y_hat_se"), c("y_hat_ir", "y_hat_se_ir"))

  data_dry <-
    data_total[sat_cat == "dryland"] %>%
    .[, .(y_hat, y_hat_se, balance)] %>%
    setnames(c("y_hat", "y_hat_se"), c("y_hat_dry", "y_hat_se_dry"))

  data_final <-
    data_dry[data_ir, on = "balance"] %>%
    .[, avg_yield := ir_share_hat * y_hat_ir + (1 - ir_share_hat) * y_hat_dry] %>%
    .[, .(sat, sat_cat, avg_yield, balance, ir_share_hat, y_hat_dry, y_hat_ir)] %>%
    .[, type := "Corn"] %>%
    .[, q1_yield := .SD[sat_cat == "[39.4,82]", avg_yield], by = balance] %>%
    .[, dif_yield := avg_yield - q1_yield]

  return(data_final)
}
```


## Bootstrap

```{r}
boot_results_data <-
  data.table(
    crop = c("Corn", "Soybean"),
    data = list(data_corn, data_soy)
  ) %>%
  mutate(boot_results = purrr::map(data, \(data) {
    parallel::mclapply(
      1:1000,
      function(i) bootstrap(i, data, sc_base, sc_dry_base),
      mc.cores = 12
    ) %>%
      rbindlist()
  })) %>%
  dplyr::mutate(se_data = purrr::map(boot_results, \(boot_results){
    boot_results[, .(avg_yield_sd = sd(avg_yield), dif_yield_sd = sd(dif_yield)), by = .(sat_cat, balance, type)]
  }))

saveRDS(boot_results_data, "Shared/Results/boot_results.rds")
```


