---
title: "Regression Analysis and Prediction"
author: "Taro Mieno"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
  tidy = FALSE,
  cache.lazy = FALSE,
  #--- figure ---#
  dpi = 400,
  fig.width = 7.5,
  fig.height = 5,
  out.width = "750px",
  out.height = "500px"
)
```

# Prepare data

```{r}
#--- read data ---#
final_data <-
  here("Shared/Data/ProcessedData/final_data.rds") %>%
  # here::here("../Shared/Data/ProcessedData/final_data.rds") %>%
  readRDS()

#--- Data used for regression analysis ---#
reg_data <-
  prepare_reg_data(
    data = final_data,
    sat_thld_m = 9, # saturated thickness has to be at least 12 meters
    ir_share_thld = 0.75, # at least 75% of total county area has to be overlapped with HPA
    balance_thld = c(-1200, 200),
    sat_cat_num = 3,
    state_ls =
      list(
        corn = c("CO", "KS", "NE", "NM", "SD", "TX", "WY"),
        soy = c("KS", "NE", "TX")
      )
  ) %>%
  data.table() %>%
  setnames("crop_type", "crop")

# saveRDS(reg_data, file = here::here("Shared/Data/reg_data.rds"))

# ggplot(reg_data$data[[1]]) +
#   geom_point(aes(y = acres_ratio, x = sat)) +
#   geom_smooth(aes(y = acres_ratio, x = sat))
```

# Regression and prediciton

## Yield

```{r}

#--- global parameters ---#


main_analysis <-
  reg_data %>%
  rowwise() %>%
  #--- the same sequence used for all the bootstrap iterations ---#
  dplyr::mutate(balance_seq = list(
    seq(
      min(data$balance),
      max(data$balance),
      length = 100
    )
  )) %>%
  dplyr::mutate(sat_seq_eval = list(
    c(10, 50, 90, 130)
  )) %>%
  dplyr::mutate(share_reg_data = list(
    data %>%
      .[ir == "ir" & ir_area_ratio >= 0.75, ] %>%
      .[, balance_avg := mean(balance), by = sc_code]
  )) %>%
  #--- the same sequence used for all the bootstrap iterations ---#
  dplyr::mutate(sat_seq = list(
    share_reg_data[, seq(min(sat),
      max(sat),
      length = 100
    )] %>%
      c(., sat_seq_eval)
  )) %>%
  #--- values of the controls to be used in prediction ---#
  dplyr::mutate(
    sandtotal_med = median(share_reg_data$sandtotal_r),
    silttotal_med = median(share_reg_data$silttotal_r),
    awc_med = median(share_reg_data$awc_r)
  ) %>%
  #++++++++++++++++++++++++++++++++++++
  #+ Main analysis
  #++++++++++++++++++++++++++++++++++++
  dplyr::mutate(yield_pred_data = list(
    yield_analysis(data, balance_seq, sat_seq_eval, sat_breaks, sat_text_data)
  )) %>%
  dplyr::mutate(share_pred_data = list(
    share_analysis(share_reg_data, sat_seq, sandtotal_med, silttotal_med, awc_med)
  )) %>%
  dplyr::mutate(avg_yield_pred_data = list(
    get_average_yield(yield_pred_data, share_pred_data)
  ))
```

```{r}
set.seed(837943)

boot_results_added$yield_pred_data_boot[[1]] %>% 
  rbindlist() %>%
  .[, .(
      # y_hat_boot = median(y_hat, na.rm = TRUE),
      y_hat_se = sd(y_hat, na.rm = TRUE),
      # dif_y_hat_boot = mean(dif_y_hat, na.rm = TRUE),
      dif_y_hat_se = sd(dif_y_hat, na.rm = TRUE)
    ),
    by = .(balance, sat, sat_cat)
    ] 

boot_results_added <-
  main_analysis[1, ]  %>%
  #--- bootsrap data ---#
  dplyr::mutate(boot_data = list(
    replicate(1000, boot(data), simplify = FALSE)
  )) %>%
  #--- get share data ---#
  dplyr::mutate(share_boot_data = list(
    lapply(
      1:length(boot_data),
      \(x) {
        boot_data[[x]] %>%
          .[ir == "ir" & ir_area_ratio >= 0.75, ] %>%
          .[, balance_avg := mean(balance), by = sc_code]
      }
    )
  )) %>%
  #--- yield analysis ---#
  dplyr::mutate(yield_pred_data_boot = list(
    parallel::mclapply(
      1:length(boot_data),
      \(x) {
        print(x)
        yield_analysis_manual(boot_data[[x]], balance_seq, sat_seq_eval, sat_breaks, sat_text_data)
      },
      mc.cores = parallel::detectCores() - 2
    )
  ))



```
```{r}
#++++++++++++++++++++++++++++++++++++
#+ Bootstrap
#++++++++++++++++++++++++++++++++++++
set.seed(837943)

balance_seq <- main_analysis$balance_seq[[1]]
  balance_seq <- main_analysis$balance_seq[[1]]
  sat_seq_eval <- main_analysis$sat_seq_eval[[1]]
  sat_breaks <- main_analysis$sat_breaks[[1]]
  sat_text_data <- main_analysis$sat_text_data[[1]]

temp <- lapply(1:500, get_coef) %>% rbindlist

main_analysis$data[[1]][sc_dry == "56031_1", ]

get_coef <- function(i) {

yield_data <- main_analysis$boot_data[[1]][[i]]
semi_res_corn <-
    semi_ols(
      semi_formula = semi_formula,
      c_formula = paste0("i(sat_cat, ref = 'dryland') + i(year, ref = 2009) + i(sc_dry, ref = '", sc_dry_base, "')"),
      # fe = "",
      cluster = "sc_dry",
      data = yield_data
    )

y_res_int <- semi_res_corn$fe_res

return_data[, mean(y_hat), by = sat_cat]
yield_data[, mean(yield), by = sat_cat]

return(
tidy(y_res_int) %>%
data.table() %>%
.[term %in% c("sat_cat::[9.01,23.1]", "sat_cat::(23.1,56.8]", "sat_cat::(56.8,216]"), estimate]
)

}
  


main_analysis <-
  main_analysis %>%
  #--- bootsrap data ---#
  dplyr::mutate(boot_data = list(
    replicate(1000, boot(data), simplify = FALSE)
  )) %>%
  #--- get share data ---#
  dplyr::mutate(share_boot_data = list(
    lapply(
      1:length(boot_data),
      \(x) {
        boot_data[[x]] %>%
          .[ir == "ir" & ir_area_ratio >= 0.75, ] %>%
          .[, balance_avg := mean(balance), by = sc_code]
      }
    )
  ))
```

```{r}
boot_data <- boot_results_added$boot_data[[1]]

balance_seq <- boot_results_added$balance_seq[[1]]
sat_seq_eval <- boot_results_added$sat_seq_eval[[1]]
sat_breaks <- boot_results_added$sat_breaks[[1]]
sat_text_data <- boot_results_added$sat_text_data[[1]]

temp <- yield_analysis(boot_data[[200]], balance_seq, sat_seq_eval, sat_breaks, sat_text_data)

ggplot(temp[sat == 50, ]) +
  geom_point(aes(y = y_hat, x = balance)) +
  ylim(0, 15)

all_results$yield_pred_data_boot[[1]][sat == 50, sd(y_hat), by = balance]

all_results$yield_pred_data_boot[[1]][sat == 10, ]

all_results$yield_pred_data_boot[[1]][sat == 10, ] %>%
ggplot(.) +
  geom_point(aes(y = y_hat, x = balance))

boot_corn <- 
  boot_results_added$yield_pred_data_boot[[1]] %>%
  rbindlist(idcol = "boot") %>%
  .[, mean(y_hat), by = .(boot, sat)]

boot_ids <- boot_corn[V1 < 11 & sat == 10, boot]

boot_results_added$boot_data[[1]][[11]] %>%
  .[, .N, by = sat_cat]

ggplot(data = boot_results_added$boot_data[[1]][[12]]) +
  geom_point(aes(y = yield, x = balance)) +
  facet_grid(sat_cat ~ .)

boot_corn[sat %in% c(10, 50), ] %>%
  dcast(boot ~ sat, value.var = "V1") %>%
  ggplot() + 
  geom_point(aes(y = `50`, x = `10`))

  ggplot(boot_corn) +
    geom_histogram(aes(x = V1)) +
    facet_grid(sat ~ .)


Check if the average yield and predicted average yield are similar.
  


```
```{r}
#++++++++++++++++++++++++++++++++++++
#+ Summarize
#++++++++++++++++++++++++++++++++++++
boot_results_added <- readRDS("Shared/Results/boot_results_added.rds")

# all_results[, data][[1]] %>%
#   ggplot() +  
#   geom_point(aes(y = yield, x = balance)) +
#   facet_grid(sat_cat ~ .)

all_results <-
  boot_results_added %>%
  # rowwise() %>%
  dplyr::mutate(yield_response_sum = list(
    yield_pred_data_boot[, .(
      # y_hat_boot = median(y_hat, na.rm = TRUE),
      y_hat_se = sd(y_hat, na.rm = TRUE),
      # dif_y_hat_boot = mean(dif_y_hat, na.rm = TRUE),
      dif_y_hat_se = sd(dif_y_hat, na.rm = TRUE)
    ),
    by = .(balance, sat, sat_cat)
    ] %>%
      .[yield_pred_data, on = c("balance", "sat")] %>%
      .[, `:=`(
        lower = y_hat - 1.96 * y_hat_se,
        upper = y_hat + 1.96 * y_hat_se,
        dif_lower = dif_y_hat - 1.96 * dif_y_hat_se,
        dif_upper = dif_y_hat + 1.96 * dif_y_hat_se
      )]
  )) %>%
  dplyr::mutate(share_sum = list(
    share_pred_data_boot[, .(
      # ir_share_hat = mean(ir_share_hat, na.rm = TRUE),
      ir_share_hat_se = sd(ir_share_hat, na.rm = TRUE)
    ),
    by = .(sat)
    ] %>%
      .[share_pred_data, on = "sat"] %>%
      .[, `:=`(
        lower = ir_share_hat - 1.96 * ir_share_hat_se,
        upper = ir_share_hat + 1.96 * ir_share_hat_se
      )]
  )) %>%
  dplyr::mutate(avg_yield_sum = list(
    avg_yield_pred_data_boot[, .(
      avg_yield_se = sd(avg_yield, na.rm = TRUE),
      dif_avg_yield_se = sd(dif_avg_yield, na.rm = TRUE)
    ),
    by = .(balance, sat)
    ] %>%
      .[avg_yield_pred_data, on = c("balance", "sat")] %>%
      .[, `:=`(
        upper = avg_yield + 1.96 * avg_yield_se,
        lower = avg_yield - 1.96 * avg_yield_se,
        dif_upper = dif_avg_yield + 1.96 * dif_avg_yield_se,
        dif_lower = dif_avg_yield - 1.96 * dif_avg_yield_se
      )]
  )) %>%
  data.table()

saveRDS(all_results, "Shared/Results/all_results.rds")
```

